### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Xayyam3389/PragmatechFoundationProject#1]
_Xəyyam, reponuzu ümumi analiz etdim və yanlış olduğunu fikirləşdiyim bəzi məqamlar var. Məsələn, bəzi [commit mesajları](https://serdarkuzucu.com/2020/04/19/git-commit-mesaji-nasil-yazilmali/) düzgün deyil. Repoya "README" hissəsi əlavə edib gördüyünüz işləri də oraya qeyd etsəniz yaxşı olar.  Hər bir tapşırıq tapşırığın adına uyğun olaraq ümumi bir qovluqda yazılmalıdır (bəzi yerlərdə bu belə deyil), yəni qısaca açıqda html, css faylları və şəkillər olmalı deyil, tapşırığa uyğun qovluq yaradılmalı və bu fayllar da onun içində olmalıdır. Css faylları "css" adlı qovluqda olmalıdır, şəkillər isə "img" adlı qovluqda ola bilər, yəni mütləq başqa, ayrı bir qovluqda olmalıdır. Uğurlar!🙂_

**Comment by Xayyam3389** [comment]
readme hissesi dediyiniz nedir?

14 noy 2021, B. tarixində 04:31 tarixində Nəzrin İsbəndiyarova <
***@***.***> yazdı:

**Comment by isbendiyarovanezrin** [comment]
_Sizdə sadəcə "readme.md" adlı fayl var, içi boşdur. Dediyim odur ki, içini gördüyünüz işlər ilə doldurun. Nümunə olaraq da [bu](https://github.com/isbendiyarovanezrin/PragmatechFrontendProject#readme) repoya baxa bilərsiniz._

**Comment by Xayyam3389** [comment]
Niyə bağladız?)

8 Nis 2022 Cum 21:24 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:

**Comment by isbendiyarovanezrin** [comment]
@Xayyam3389, issue'ları bağlamaq lazımdır (açıq o halda saxlamaq olar ki, issue'da həll edilməmiş nəsə qalsın və sairə). Qalanını siz edərsiniz, zəhmət olmasa.🙂

**Comment by Xayyam3389** [comment]
Nç bununla barışa bilmərəm😑😑

8 Nis 2022 Cum 21:30 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:
