### ISSUE TITLE
Şəkil adlarında boşluq olmamalıdır

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Xayyam3389/PragmatechFoundationProject#10]
[Şəkil adlarında](https://github.com/Xayyam3389/PragmatechFoundationProject/tree/master/ProjectFrontEnd/My_Project/img) boşluq olmalı deyil və şəkil adı şəkli izah etməlidir, yəni adına baxanda nə olduğu bilinməlidir. Məsələn, bu "WhatsApp Image 2021-11-28 at 22.46.51.jpeg" şəkil adı düzgün deyil.

**Comment by Xayyam3389** [comment]
Aydındır. Qeyd olunan problemləri aradan qaldırıb update edəcəm

30 Kas 2021 Sal 19:20 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:
