### ISSUE TITLE
Bütün teqlərə class adı verməyə çalışın

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Xayyam3389/PragmatechFoundationProject#13]
**[Bu](https://github.com/Xayyam3389/PragmatechFoundationProject/blob/master/ProjectFrontEnd/My_Project/css/style.css#L56)** hissədə `.navbar-list ul li a` yazmaq yerinə `a` teqinə class adı vermək daha oxunaqlı olmaz, sizcə? Məncə, elə olar. Məsələn, `nav-link` və ya elə adicə `link` adında class adı verə bilərsiniz. Həm yazılışı daha qısa olduğu üçün daha oxunaqlı olar, həm də bu class'dan başqa yerdə də istifadə edə bilərsiniz. Elə ən əsası da budur. Başqa yerdə istifadə edə bilmək.

**Comment by Xayyam3389** [comment]
Ussueni indi gördüm sorry.Diqqətiniz üçün çox sağolun. Aha düz deirsiz
yazdığımız səhifəni tamamladıqdan sonra optimallaşdırmaqa çalışacıq ,clas
adlarını və ümumi hər yerdə istifadə eDiləsi clasları ayıracıq

1 Ara 2021 Çar 14:24 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:
