### ISSUE TITLE
JavaScript faylları "js" adlı qovluqda olmalıdır

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Xayyam3389/PragmatechFoundationProject#26]
Qovluq adı mütləq "js" olmalı deyil, amma içində JavaScript faylları olduğu üçün JavaScript ilə bağlı bir ad olmalıdır. Yaxşı olardı ki, "js" olsun.

**Comment by Xayyam3389** [comment]
Oldu nəzərə alacam təşəkür edirəm

20 Ara 2021 Pzt 00:40 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:
