### ISSUE TITLE
JavaScriptdən bu məsələləri işləməyə çalışın

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Xayyam3389/PragmatechFoundationProject#27]
**[Bu](https://www.w3resource.com/javascript-exercises/javascript-basic-exercises.php)** linkdə 150 dənə çox da çətin olmayan Javascript məsələləri var. Boş vaxtlarınızda işləyə bilərsiniz.

**Comment by Xayyam3389** [comment]
Çox sağolun Nəzrin xanım

20 Ara 2021 Pzt 21:51 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:
