### ISSUE TITLE
Front-End Challenges

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Xayyam3389/PragmatechFoundationProject#28]
Aşağıdakı linkdə olan challenge'lərdən birinə başlaya bilərsiniz. Maraqlıdır.🙂

- _[**Link**](https://css-tricks.com/front-end-challenges "Mənə klik et!")_

**Comment by Xayyam3389** [comment]
👍👍👍👍👍👍👍👍👍👍

20 dek 2021, B.e. tarixində 09:52 tarixində Nəzrin İsbəndiyarova <
***@***.***> yazdı:
