### ISSUE TITLE
Repo 6 gündür update olunmur

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Xayyam3389/PragmatechFoundationProject#39]
Çalışın hər gün update edin.

**Comment by Xayyam3389** [comment]
Bayramdır istrahət edirik mudir)))

2 Oca 2022 Paz 23:28 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:

**Comment by isbendiyarovanezrin** [comment]
Haha mən bitdi deyə bilirdim bayramı😅

**Comment by Xayyam3389** [comment]
Elə bildim yazmısan məm bitdi demədən bitməz)
 Yox biz 5nə kimi bayram elan eləmişik ,açmıycam kompun üzünü)

2 Oca 2022 Paz 23:30 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:

**Comment by isbendiyarovanezrin** [comment]
Gərək elə yazardım hahaha

**Comment by Xayyam3389** [comment]
Yazmış qədər varsan day)) sənə görə bir iki kod yazıb update edicəm

2 Oca 2022 Paz 23:38 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:

**Comment by Xayyam3389** [comment]
Müəllimm heç bu qədər sıxmır bizi))

3 Oca 2022 Pzt 00:06 tarihinde Xayyam Gasimzade ***@***.***> şunu
yazdı:

**Comment by isbendiyarovanezrin** [comment]
Mən çox ciddiyə almışam deyəsən bu işi😅

**Comment by isbendiyarovanezrin** [comment]
Vallah veycimə olmasa heç nə yazmaram. Düzünə qalsa heç yaz deyən də yoxdur. Amma istəyirəm ki, hamı hər gün maraqlı nəsə yaratsın, yazsın baxım. Bir gün reponu update olunmayan görəndə əsəbiləşirəm.😅

**Comment by Xayyam3389** [comment]
Heç kurs sənin qədər fikirləşmir tələbələri)) yo yaxşı elirsən  başqalarını
deyə bilmərəm ama mənə yaz ussue)

3 Oca 2022 Pzt 00:17 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:

**Comment by isbendiyarovanezrin** [comment]
Birinci cümləniz o qədər düzdür ki😅🤗

**Comment by isbendiyarovanezrin** [comment]
Yaz dediyinizə peşman edəcəm haha

**Comment by Xayyam3389** [comment]
Görəkda kim kimi peşman edəcək)))

3 Oca 2022 Pzt 00:24 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:
