### ISSUE TITLE
.html uzantılı faylları qovluqda yazmağa ehtiyac yoxdur

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Xayyam3389/PragmatechFoundationProject#4]
[Burada](https://github.com/Xayyam3389/PragmatechFoundationProject/tree/master/Works/Week%205%20day%203) html faylını "html" adlı qovluqda yazmısınız. Düzgün deyil. [Bu](https://link.medium.com/EDT8laQmslb) qaynaq faydalı ola bilər.

**Comment by Xayyam3389** [comment]
bəs müəllim demisdi axı bütün faylları ayrı qovluqlara yerlə.dirin.Ona görə
hamsını qovluqlara atmışam. Necə etməliyəm. Hansılar qovluqda olmalıdı
hansılar ümumidə,? atdığınız link açılmadı

25 noy 2021, C.a. tarixində 10:25 tarixində Nəzrin İsbəndiyarova <
***@***.***> yazdı:

**Comment by isbendiyarovanezrin** [comment]
".html" uzantılı fayllardan başqa hər şeyi ayrı bir qovluqda yazmaq lazımdır. Yerləşdirdiyim link açılır, bir daha yoxlayın. Medium məqaləsidir.
