### ISSUE TITLE
Repo 10 gündür update olunmur

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Xayyam3389/PragmatechFoundationProject#44]
Bayram bitib artıq😅

**Comment by Xayyam3389** [comment]
Salam Nəzrin, bugünnən start verirəm)

6 Oca 2022 Per 16:06 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:

**Comment by isbendiyarovanezrin** [comment]
Salam, yaxşı🙂

**Comment by Xayyam3389** [comment]
İndi mənim mentorum kimdi?)

6 Oca 2022 Per 19:49 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:

**Comment by isbendiyarovanezrin** [comment]
Kağız üstündə Məhəmməd haha

**Comment by Xayyam3389** [comment]
Bəs mən dərdimi kimə diyəcəm, sənə deim?

6 Oca 2022 Per 19:53 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:

**Comment by isbendiyarovanezrin** [comment]
Və ya kursa gəl, köməklik edərik.

**Comment by Xayyam3389** [comment]
Oke👍👍👍

6 Oca 2022 Per 19:56 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:

**Comment by Xayyam3389** [comment]
Sənnən başqa cavablandıran olmuyub son iki aydı)

6 Oca 2022 Per 19:56 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:

**Comment by Xayyam3389** [comment]
Sənə laiq tələbə olacaqıma söz verirəm😁😁

6 Oca 2022 Per 19:59 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:

**Comment by isbendiyarovanezrin** [comment]
😅😄🤗
