### ISSUE TITLE
Şəkillər üçün iki qovluq açmağa ehtiyac yoxdur, biri bəsdir

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Xayyam3389/PragmatechFoundationProject#5]
**[Bu](https://github.com/Xayyam3389/PragmatechFoundationProject/tree/master/Works/Week%205%20day%201/Flex_vs_grid/TaskWithGrid)** qovluqda içində şəkillər olan iki qovluq var. Biri bəsdir, "wireframe" adında olanı silin, məncə. Başqa yerlərdə də bu hal gözümə dəydi, düzəliş edin.

**Comment by Xayyam3389** [comment]
orda birinin icinde istifade olunan şəkillər və logolar və s.  O birində
isə həmin səhifənin wireframesi var. Onlar hamısı bir papkada olmalıdı,?
html fayl necəə, onları ayrı papkaya yığmayım,?


25 noy 2021, C.a. tarixində 10:42 tarixində Nəzrin İsbəndiyarova <
***@***.***> yazdı:

**Comment by isbendiyarovanezrin** [comment]
Harada istifadə olunacağından asılı olmayaraq şəkillər hamısı bir qovluqda olmalıdır.

**Comment by Xayyam3389** [comment]
çox təşəkkür edirəm. Bütün fayllarda dəyişiklik edib düzəldəcəm

25 noy 2021, C.a. tarixində 11:16 tarixində Nəzrin İsbəndiyarova <
***@***.***> yazdı:
